<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="gkillare-win87" failures="1" tests="6" name="mtestcases.TC_EBT" time="149.144" errors="0" timestamp="2024-12-26T11:57:03 IST" skipped="0">
  <testcase classname="mtestcases.TC_EBT" name="RefundOfSale" time="26.760"/>
  <system-out/>
  <testcase classname="mtestcases.TC_EBT" name="VoidOfRefundWithoutsale" time="21.516"/>
  <system-out/>
  <testcase classname="mtestcases.TC_EBT" name="VoidOfRefundWithoutsale" time="22.408">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at base.BaseClass.performVoidTransaction(BaseClass.java:425)
at mtestcases.TC_EBT.VoidOfRefundWithoutsale(TC_EBT.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- VoidOfRefundWithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_EBT" name="VoidOfSale" time="26.764"/>
  <system-out/>
  <testcase classname="mtestcases.TC_EBT" name="RefundOfSale" time="28.347"/>
  <system-out/>
  <testcase classname="mtestcases.TC_EBT" name="VoidOfSale" time="23.349"/>
  <system-out/>
</testsuite> <!-- mtestcases.TC_EBT -->
