<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="gkillare-win87" failures="2" tests="17" name="testcases.Demo" time="352.073" errors="0" timestamp="2024-03-18T14:34:20 IST" skipped="0">
  <testcase classname="testcases.Demo" name="F_creditSale" time="33.712"/>
  <system-out/>
  <testcase classname="testcases.Demo" name="F_creditSale" time="35.057"/>
  <system-out/>
  <testcase classname="testcases.Demo" name="F_creditSale" time="39.325"/>
  <system-out/>
  <testcase classname="testcases.Demo" name="F_creditSale" time="29.291"/>
  <system-out/>
  <testcase classname="testcases.Demo" name="F_creditSale" time="23.367"/>
  <system-out/>
  <testcase classname="testcases.Demo" name="SECOUNDARY_creditAndDebitSale" time="39.913"/>
  <system-out/>
  <testcase classname="testcases.Demo" name="SECOUNDARY_creditAndDebitSale" time="31.384"/>
  <system-out/>
  <testcase classname="testcases.Demo" name="SECOUNDARY_creditAndDebitSale" time="27.593"/>
  <system-out/>
  <testcase classname="testcases.Demo" name="VoidAllTransactions" time="8.728">
    <failure message="Processor ID MissMatch....... expected [024887638] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Processor ID MissMatch....... expected [024887638] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testcases.Demo.VoidAllTransactions(Demo.java:303)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VoidAllTransactions -->
  <system-out/>
  <testcase classname="testcases.Demo" name="VoidAllTransactions" time="12.445"/>
  <system-out/>
  <testcase classname="testcases.Demo" name="VoidAllTransactions" time="12.338"/>
  <system-out/>
  <testcase classname="testcases.Demo" name="VoidAllTransactions" time="7.523"/>
  <system-out/>
  <testcase classname="testcases.Demo" name="VoidAllTransactions" time="8.035">
    <failure message="Processor ID MissMatch....... expected [024887638] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Processor ID MissMatch....... expected [024887638] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testcases.Demo.VoidAllTransactions(Demo.java:303)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VoidAllTransactions -->
  <system-out/>
  <testcase classname="testcases.Demo" name="VoidAllTransactions" time="10.541"/>
  <system-out/>
  <testcase classname="testcases.Demo" name="VoidAllTransactions" time="11.194"/>
  <system-out/>
  <testcase classname="testcases.Demo" name="VoidAllTransactions" time="8.791"/>
  <system-out/>
  <testcase classname="testcases.Demo" name="VoidAllTransactions" time="12.836"/>
  <system-out/>
</testsuite> <!-- testcases.Demo -->
