<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="gkillare-win87" failures="7" tests="40" name="testcases.processorfailourchase.TC_ProcessorFailour10" time="906.016" errors="0" timestamp="2024-03-01T11:32:04 IST" skipped="0">
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="DebitSale" time="19.176"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="DebitSale" time="26.054"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="P_FSA" time="30.686"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="Ewic_Transactions" time="71.487"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="P_EBT" time="30.286"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="P_EBT" time="23.809"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="F_creditSale" time="30.654"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="P_HardCode__FSA" time="41.613"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="P_HardCode__EBT" time="28.506"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="SECOUNDARY_creditAndDebitSale" time="17.063"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="SECOUNDARY_creditAndDebitSale" time="25.348"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="SECOUNDARY_creditAndDebitSale" time="55.790"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="P_SECOUNDARY__FSA" time="31.587"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="P_SECOUNDARY__EBT" time="24.856"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="P_SECOUNDARY__EBT" time="30.716"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="10.659"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="8.749"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="8.854"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="9.048">
    <failure message="Processor ID MissMatch....... expected [024887638] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Processor ID MissMatch....... expected [024887638] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testcases.processorfailourchase.TC_ProcessorFailour10.VoidAllTransactions(TC_ProcessorFailour10.java:859)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VoidAllTransactions -->
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="2.286"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="49.229">
    <failure message="Processor ID MissMatch....... expected [024887638] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Processor ID MissMatch....... expected [024887638] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testcases.processorfailourchase.TC_ProcessorFailour10.VoidAllTransactions(TC_ProcessorFailour10.java:859)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VoidAllTransactions -->
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="9.518">
    <failure message="Processor ID MissMatch....... expected [024887638] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Processor ID MissMatch....... expected [024887638] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testcases.processorfailourchase.TC_ProcessorFailour10.VoidAllTransactions(TC_ProcessorFailour10.java:859)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VoidAllTransactions -->
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="8.326"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="2.397"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="8.823">
    <failure message="Processor ID MissMatch....... expected [024887638] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Processor ID MissMatch....... expected [024887638] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testcases.processorfailourchase.TC_ProcessorFailour10.VoidAllTransactions(TC_ProcessorFailour10.java:859)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VoidAllTransactions -->
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="11.472">
    <failure message="Processor ID MissMatch....... expected [577000322896] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Processor ID MissMatch....... expected [577000322896] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testcases.processorfailourchase.TC_ProcessorFailour10.VoidAllTransactions(TC_ProcessorFailour10.java:859)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VoidAllTransactions -->
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="2.383"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="2.435"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="2.436"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="9.775">
    <failure message="Processor ID MissMatch....... expected [024887638] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Processor ID MissMatch....... expected [024887638] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testcases.processorfailourchase.TC_ProcessorFailour10.VoidAllTransactions(TC_ProcessorFailour10.java:859)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VoidAllTransactions -->
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="VoidAllTransactions" time="8.668">
    <failure message="Processor ID MissMatch....... expected [024887638] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Processor ID MissMatch....... expected [024887638] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testcases.processorfailourchase.TC_ProcessorFailour10.VoidAllTransactions(TC_ProcessorFailour10.java:859)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VoidAllTransactions -->
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="ResetCount" time="34.980"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="afterResetDebitSale" time="33.538"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="afterResetDebitSale" time="20.193"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="P_AfterReset_EBT" time="24.373"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="P_AfterReset_EBT" time="26.211"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="P_AfterReset_FSA" time="36.357"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="F_AfterReset_creditSale" time="27.546"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="F_AfterReset_creditSale" time="39.995"/>
  <system-out/>
  <testcase classname="testcases.processorfailourchase.TC_ProcessorFailour10" name="DebitSaleLastOne" time="20.134"/>
  <system-out/>
</testsuite> <!-- testcases.processorfailourchase.TC_ProcessorFailour10 -->
