<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="gkillare-win87" failures="53" tests="396" name="mtestcases.TC_CIandCRM" time="6637.644" errors="0" timestamp="2024-12-23T19:13:08 IST" skipped="0">
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="18.135"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.352"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.504"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="14.306"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="19.502"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.651"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.307">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCIRefundOfSale(TC_CIandCRM.java:91)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="14.722"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.639"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.883"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.641"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.074"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="15.651">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCIRefundOfSale(TC_CIandCRM.java:91)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="12.654">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCIRefundOfSale(TC_CIandCRM.java:91)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="19.404"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="18.528"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="18.373"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.155"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.695"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="16.383"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.504"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.655"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.644"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="14.667"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.598"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="14.745">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCIRefundOfSale(TC_CIandCRM.java:91)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.697"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="19.874"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="15.392">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCIRefundOfSale(TC_CIandCRM.java:91)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.356"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="22.356"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.702"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.262"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.652"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.551"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.678"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="19.585"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="15.908">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCIRefundOfSale(TC_CIandCRM.java:91)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.489"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="15.598">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCIRefundOfSale(TC_CIandCRM.java:91)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.039"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.629"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="18.018"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="18.905"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="14.770"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.481"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="14.847"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="14.631"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.660"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="12.950">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCIRefundOfSale(TC_CIandCRM.java:91)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="14.898">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCIRefundOfSale(TC_CIandCRM.java:91)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="15.918">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCIRefundOfSale(TC_CIandCRM.java:91)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="12.194">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCIRefundOfSale(TC_CIandCRM.java:91)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.062"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="19.738"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="14.622">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCIRefundOfSale(TC_CIandCRM.java:91)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.513"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.022"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="20.684"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="19.271"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.411"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.176"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="16.996"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="17.259"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIRefundOfSale" time="13.997"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="14.776">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCIVoidOfSale(TC_CIandCRM.java:128)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.464"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="14.937">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCIVoidOfSale(TC_CIandCRM.java:128)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="19.368"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.255"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.992"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.820"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.458"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="18.619"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.491"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="19.171"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="15.645">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCIVoidOfSale(TC_CIandCRM.java:128)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.304"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.420"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="14.801"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.566"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.360"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.310"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.349"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="15.911">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCIVoidOfSale(TC_CIandCRM.java:128)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="19.716"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="15.887">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCIVoidOfSale(TC_CIandCRM.java:128)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="18.108"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.234"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="15.680">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCIVoidOfSale(TC_CIandCRM.java:128)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="19.858"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.477"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="16.123">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCIVoidOfSale(TC_CIandCRM.java:128)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="18.327"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="18.170"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.754"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.500"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="18.040"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="15.222"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.692"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.475"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.935"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="13.258">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCIVoidOfSale(TC_CIandCRM.java:128)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.515"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="16.537"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="15.975">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCIVoidOfSale(TC_CIandCRM.java:128)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.638"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="14.584">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCIVoidOfSale(TC_CIandCRM.java:128)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="19.833"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="20.131"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.607"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="16.872"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="16.868"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="14.560"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="15.833"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="15.071">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCIVoidOfSale(TC_CIandCRM.java:128)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.369"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="16.674"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="15.393"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="14.708"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.369"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.185"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.465"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="15.979">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCIVoidOfSale(TC_CIandCRM.java:128)
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="18.306"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.604"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="14.658"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.480"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.224"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfSale" time="17.414"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.424"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.234"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="14.739">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCIVoidOfRefundwithoutsale(TC_CIandCRM.java:166)
at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIVoidOfRefundwithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="19.269"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="20.459"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="19.780"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.619"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="14.497"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.624"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.505"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="14.795"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.619"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="14.900"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.481"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.385"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.166"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.565"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.174"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.993"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.360"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.835"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.529"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.283"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.195"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="15.061"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.235"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.277"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.721"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.497"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.609"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.798"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.378"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="19.196"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.101"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.272"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.252"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.766"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.089"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="19.039"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="16.611"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="19.099"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="14.908"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.319"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.045"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.828"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.420"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="14.286"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.741"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="14.173"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="15.226">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCIVoidOfRefundwithoutsale(TC_CIandCRM.java:166)
at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCIVoidOfRefundwithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="19.136"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.799"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.035"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="20.501"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.391"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.942"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="19.140"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.626"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.866"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="19.661"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.249"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.625"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.937"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="17.318"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCIVoidOfRefundwithoutsale" time="18.367"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="13.983">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCRMRefundOfSale(TC_CIandCRM.java:204)
at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.045"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.227"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="17.420"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="14.279">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCRMRefundOfSale(TC_CIandCRM.java:204)
at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.794"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="35.824"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.661"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="17.295"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.154"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="34.834"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.777"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="15.895"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="15.825"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="15.991"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="13.299">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCRMRefundOfSale(TC_CIandCRM.java:204)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.463"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="15.993"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="15.364"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.076"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="15.955"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="15.257">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCRMRefundOfSale(TC_CIandCRM.java:204)
at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.333"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.476"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="13.424"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="14.172">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCRMRefundOfSale(TC_CIandCRM.java:204)
at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.905"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="17.695"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.208"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="15.732"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="20.873"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="15.860"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="14.955">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCRMRefundOfSale(TC_CIandCRM.java:204)
at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.021"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.187"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="17.621"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.170"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="13.316"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="17.877"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="17.946"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="15.799"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.006"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="18.045"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="13.694"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="14.611">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCRMRefundOfSale(TC_CIandCRM.java:204)
at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.134"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.273"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.111"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.458"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="11.576">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCRMRefundOfSale(TC_CIandCRM.java:204)
at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.024"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.171"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="15.837"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="14.116">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCRMRefundOfSale(TC_CIandCRM.java:204)
at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="11.024">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCRMRefundOfSale(TC_CIandCRM.java:204)
at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.134"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.808"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="13.441">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCRMRefundOfSale(TC_CIandCRM.java:204)
at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="17.739"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="17.724"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.179"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="15.867"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="14.529">
    <failure message="Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Refund did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performRefundTransaction(TC_CIandCRM.java:348)
at mtestcases.TC_CIandCRM.testCRMRefundOfSale(TC_CIandCRM.java:204)
at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMRefundOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="16.588"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="12.984"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="12.898"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMRefundOfSale" time="13.326"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="15.781">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfSale(TC_CIandCRM.java:240)
at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.405"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.497"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="13.051"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.100"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="12.081">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfSale(TC_CIandCRM.java:240)
at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.071"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.144"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="14.263">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfSale(TC_CIandCRM.java:240)
at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.830"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="14.831">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfSale(TC_CIandCRM.java:240)
at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="18.337"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="15.659"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="18.070"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.529"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="11.008">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfSale(TC_CIandCRM.java:240)
at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.707"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="13.491"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.135"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.164"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="14.414"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="18.198"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.080"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="15.803"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.722"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.116"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.949"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="15.979"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="15.553"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="13.307"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="14.669">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfSale(TC_CIandCRM.java:240)
at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.046"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="19.166"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.137"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.847"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="15.355"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.255"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.826"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="18.562"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="15.992"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="13.603"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.032"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.044"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="13.135"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.505"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="13.457"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="17.899"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="17.102"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="13.372">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfSale(TC_CIandCRM.java:240)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.175"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="12.857"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.548"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.401"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="15.777"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="13.801">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfSale(TC_CIandCRM.java:240)
at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="17.775"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.380"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="15.002">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfSale(TC_CIandCRM.java:240)
at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="14.284">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfSale(TC_CIandCRM.java:240)
at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="15.834"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.201"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.606"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="14.245">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfSale(TC_CIandCRM.java:240)
at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="13.583">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfSale(TC_CIandCRM.java:240)
at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfSale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="15.881"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="18.557"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfSale" time="16.035"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.340"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="17.997"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="15.519"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="13.033"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.407"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="36.998">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfRefundwithoutsale(TC_CIandCRM.java:276)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfRefundwithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.906"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.089"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="15.262"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.988"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.336"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="13.278"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="13.828"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.648"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="17.774"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="18.873"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="15.977"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="15.972"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="17.385"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.373"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="15.981"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.203"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.275"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.343"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="15.676"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.299"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.492"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.158"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="17.633"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.634"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="17.696"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.038"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="17.774"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="18.062"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="15.575"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="13.664"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="13.235"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="17.969"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="18.080"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="35.219"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.106"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.339"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="12.913"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="10.641">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfRefundwithoutsale(TC_CIandCRM.java:276)
at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfRefundwithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="13.721"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.501"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.643"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="13.443"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.121"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.025"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.048"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="19.309"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="13.511">
    <failure message="Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Amount is zero ; We are not processes Void did not expect [0.00] but found [0.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at mtestcases.TC_CIandCRM.Token_performVoidTransaction(TC_CIandCRM.java:415)
at mtestcases.TC_CIandCRM.testCRMVoidOfRefundwithoutsale(TC_CIandCRM.java:276)
at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testCRMVoidOfRefundwithoutsale -->
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.942"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="17.610"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="18.068"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.301"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.720"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.498"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="17.809"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.534"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.130"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="17.967"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="18.322"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.030"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="16.145"/>
  <system-out/>
  <testcase classname="mtestcases.TC_CIandCRM" name="testCRMVoidOfRefundwithoutsale" time="18.301"/>
  <system-out/>
</testsuite> <!-- mtestcases.TC_CIandCRM -->
